"""Add user_id to weather

Revision ID: ccde3f950fa8
Revises: 
Create Date: 2024-06-23 19:26:01.832109

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ccde3f950fa8"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "weather", sa.Column("id", sa.Integer(), autoincrement=True, nullable=False)
    )
    op.add_column("weather", sa.Column("user_id", sa.Integer(), nullable=False))
    op.alter_column(
        "weather",
        "city",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=20),
        existing_nullable=False,
    )
    op.create_foreign_key(None, "weather", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "weather", type_="foreignkey")
    op.alter_column(
        "weather",
        "city",
        existing_type=sa.String(length=20),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.drop_column("weather", "user_id")
    op.drop_column("weather", "id")
    # ### end Alembic commands ###
